### PR TITLE
Feature/new pledge form

### PR DESCRIPTION
**Pull request by PeteJStewart**
Added new pledge form and lambda/function endpoints.
I've also added webpack and a few other tools for bundling the code so it works in IE.

### CODE REVIEW

**Comment by PeteJStewart** [comment]
I feel like these tests have not passed because I've pushed a feature branch and they should only run on master?

**Comment by eugenebolshakov** [comment]
@PeteJStewart Hi Pete!

I think these failed checks mean that Netlify couldn't deploy the site from this branch. It's configured to create preview deployments from PRs and this one is failing for some reason. 

If you have access to Netlify, you should be able to see the deployment logs here: https://app.netlify.com/sites/inspiring-golick-7b7a75/deploys/5efa0fb74e93540008f26c22

I haven't looked properly, but there seem to be just these two lines at the bottom which indicate some kind of failure, but don't really explain what exactly happened:

```
5:00:24 PM: Failing build: Failed to build site
5:00:24 PM: Failed during stage 'building site': Deploy directory 'build' does not exist
```

Do you think you could look into it and try to figure out what's going on?

**Comment by PeteJStewart** [comment]
@eugenebolshakov Hi Eugene,

Yeah I look at that and couldn't see any obvious reason.  I've run the build code locally, and it seems to work as expected.
I was wondering if it was to do with it not being on the master branch, but I guess not.
I'm not entirely sure how to debug this, as the fail message isn't particularly helpful.

**Comment by eugenebolshakov** [comment]
@PeteJStewart Just noticed this line in the logs:

```
7:21:42 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'npm run lambda-build' versus 'middleman build --verbose' in the Netlify UI
```

I think what this may mean is that Netlify builds the lambdas, but doesn't build the site itself.

Looks like you just pushed a fix for this while I was writing this comment though :)

**Comment by PeteJStewart** [comment]
I seem to have resolved that now.
It was because I needed to add a netlify.toml config file to transpile the lambda functions, 
but didn't realise that this would stop the middleman build command from running.
I've simply added the `bundle exec middleman build` command to this build config and now it all seem to be passing.

**Comment by PeteJStewart** [comment]
@eugenebolshakov If you're happy with that, feel free to merge! ;)

**Comment by eugenebolshakov** [comment]
@PeteJStewart Great, thanks for sorting out the issue. I'll look into the changes properly asap and will let you know if I have any feedback.

Not sure if you've already done it, but might be a good idea to ask @annavictoriahughes to take a look at the preview to make sure she's happy with the way it looks / works.

**Comment by eugenebolshakov** [comment]
@jamoboggins Thanks for merging this. I wrote above that I'd provide feedback, but of course it's taken me ages to do it, so good call on merging it as it works fine. 

I've made some tweaks to this locally that I haven't pushed yet, I'll open a new PR for those.

**Pull request merged**
